#!/bin/sh

wid=$1
class=$2
instance=$3
title=$(xtitle "$wid")

if [ "$class" = yakuake ] ; then
  echo "sticky=on state=floating"
  xdotool windowmove $wid 0 30
fi

if [ "$class" = krunner ] ; then
  echo "sticky=on state=floating"
  xdotool windowmove $wid 600 35
fi

if [ "$class" = plasmashell ] ; then
  echo "state=floating"
fi
